version: '3.8'
services:
  mysql:
    image: il12564/trio-task-db
    environment:
      MYSQL_DATABASE: flask-db
      MYSQL_ROOT_PASSWORD: password123
    networks:
      - mynetwork
  flask-app:
    image: il12564/trio-task-app
    depends_on:
      - mysql
    networks:
      - mynetwork
    environment:
      MYSQL_ROOT_PASSWORD: password123
  nginx:
    image: nginx:latest
    ports:
      - target: 80
        published: 80
    depends_on:
      - flask-app
    volumes:
      - type: bind
        source: nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    networks:
      - mynetwork
networks:
  mynetwork:
